### ISSUE TITLE
Feature request: disable polling/notifications

### ISSUE THREAD

**Issue by enote-kane** [camunda-community-hub/camunda-platform-7-mail#127]
### Is your feature request related to a problem? Please describe.

As an operator of a Camunda BPM 7 installation, I want to disable any polling mechanism, so that I can connect using an SMTP-only server (no POP/IMAP access).

### Describe the solution you'd like

As soon as I do not configure `mail.store.protocol`, integration with the Camunda-internal notification system shall be skipped entirely.

### Describe alternatives you've considered

none, since I am an operator.

### Additional context

When using a mail service such as SendGrid or similar, often there is no IMAP or POP3 access available (nor wanted) since using these is for send-only cases without any mailboxes in the traditional sense.

**Comment by jonathanlukas** [comment]
Hello @enote-kane ,

thank you for providing this input. 

Have you already configuring a pure SMTP connection and only use the send connector?

Due to the project structure (and target audience), there is no need to have a send-only mode.

What would you think about having a separate sendgrid connector just like it is in place in Camunda 8?

**Comment by enote-kane** [comment]
Hi @jonathanlukas , thank you for the response.

Well, I am using the camunda-bpm-run Docker container and have only followed the docs here: https://github.com/camunda-community-hub/camunda-platform-7-mail/blob/main/extension/spring-boot/README.md

And as soon as I skip configuring the store protocol, the Camunda BPM Run startup throws the following at me:
```
<#4c95cfe7> javax.mail.NoSuchProviderException: Invalid protocol: null
        at javax.mail.Session.getProvider(Session.java:489)
        at javax.mail.Session.getStore(Session.java:588)
        at javax.mail.Session.getStore(Session.java:568)
        at javax.mail.Session.getStore(Session.java:554)
        at org.camunda.bpm.extension.mail.service.JakartaMailService.provideStore(JakartaMailService.java:38)
        at org.camunda.bpm.extension.mail.service.JakartaMailService.getFolder(JakartaMailService.java:60)
        at org.camunda.bpm.extension.mail.notification.MailNotificationService.supportsIdle(MailNotificationService.java:121)
        ... 26 common frames omitted
Wrapped by: <#b5ceb084> java.lang.RuntimeException: javax.mail.NoSuchProviderException: Invalid protocol: null
        at org.camunda.bpm.extension.mail.notification.MailNotificationService.supportsIdle(MailNotificationService.java:134)
        at org.camunda.bpm.extension.mail.notification.MailNotificationService.getNotificationWorker(MailNotificationService.java:98)
        at org.camunda.bpm.extension.mail.notification.MailNotificationService.doStart(MailNotificationService.java:71)
        at org.camunda.bpm.extension.mail.notification.MailNotificationService.start(MailNotificationService.java:63)
        ... 23 common frames omitted
```

Would it be that hard to add an enable/disable switch to the `MailNotificationService`?

In the top-level README, I see 3 connectors made available by this project, so the expectation I had was that I could configure each of them, not that configuration for all would be mandatory.

**Comment by jonathanlukas** [comment]
Hi @enote-kane ,

thank you for the concrete feedback. 

I would now put it like this:

When using spring-boot, I want to be able to disable the notification service.

That's quite easy to ship I guess.

The first proposal sounded like you want to be able to disable several connectors... that would have been much harder.

**Comment by enote-kane** [comment]
OK, sorry for misleading terminology. Feel free to adjust it then.

But essentially your first interpretation wasn't that wrong. Essentially I only want the "mail-send" connector to be provided in the Camunda BPM engine that I am managing for our devs/users, so yeah, I don't want them to be able to listen on incoming emails, neither to allow anyone to delete some emails.

I mean it would still be OK if the connector itself was there but just throwing an error when attempting to actively use it - if that makes any difference.

**Comment by jonathanlukas** [comment]
I will handle it that way first.

The second request could then be to preserve the connectors as they are, but splitting them up in different modules, so that they could be excluded/seperately included?

**Comment by enote-kane** [comment]
ACK, sounds like a plan! Thank you

**Comment by martinburrows** [comment]
Hi @jonathanlukas, this would be a useful fix for me too - do you have any upcoming plans to create a release? :)

**Comment by jonathanlukas** [comment]
I will create a release this week
