### ISSUE TITLE
Feature request Springboot 3.x.x and Camunda 7.20 support

### ISSUE THREAD

**Issue by amardeep2006** [camunda-community-hub/camunda-platform-7-mail#195]
### Is your feature request related to a problem? Please describe.

The mail connector and springboot starter need to be upgraded as per latest Camunda 7 version 7.20.0 .

### Describe the solution you'd like

It must be upgraded for Springboot 3 support.

### Describe alternatives you've considered

I could still use 1.5.1 core but I had to create my own Config class in Springboot project as MailConnectorConfiguration.java is not scanned by spring boot 3.

### Additional context

I will raise a PR that can be used as inspiration for this change.

**Comment by amardeep2006** [comment]
I raised a PR that can be referenced for this implementation.
I made following changes:
1. Add HTTL to bpmn files
2. Java version 17
3. /META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports for springboot 3 support.

https://github.com/camunda-community-hub/camunda-platform-7-mail/pull/196

**Comment by jonathanlukas** [comment]
See release 7.20.1

**Comment by amardeep2006** [comment]
Thanks @jonathanlukas I will test and share feedback if I see issue.
So Camunda 7.20 does work with springboot 3.2 ? I was using 3.1.x . Can I upgrade to 3.2 in my project ?

**Comment by jonathanlukas** [comment]
@amardeep2006 it should not break between 3.1 and 3.2, but as Camunda 7.20 only supports 3.1, you should stick to 3.1.

If this breaks something on the mail connector side (it should not, but you never know...), please file a bug report
