### ISSUE TITLE
Class Not Found Exception

### ISSUE THREAD

**Issue by TEJAPS** [camunda-community-hub/camunda-platform-7-mail#26]
Getting this error:
Caused by: java.lang.ClassNotFoundException: org.camunda.commons.utils.cache.Cache

**Comment by saig0** [comment]
Hi @TEJAPS,

you need to share more details about the case, like the version of the extension and of Camunda BPM. 
How do you use the Camunda BPM (e.g. Camunda Run, Tomcat distro, etc.)?

Please share everything that someone can reproduce the behavior :)

**Comment by chiranjeevibmse** [comment]
Even i have faced same issue, with 7.15.0 version.
Where i just created the Camunda Spring boot Application and added mail dependency

What is have missed is the [Connector Documentation](https://docs.camunda.org/manual/latest/user-guide/process-engine/connectors/), as per this i have added the depedency of Camunda BOM, camunda-connect-core,camunda-engine-plugin-connect

**Comment by saig0** [comment]
@chiranjeevibmse thanks for sharing! 

Feel free to improve the docs by opening a PR :balloon:
