### ISSUE TITLE
Version 1.3.0 is not available on maven central

### ISSUE THREAD

**Issue by martinschickbichlerspie** [camunda-community-hub/camunda-platform-7-mail#27]
The latest version available via maven is the old 1.2.0 version.

Also, the current version of the README still mentions 1.2.0 instead of the latest release, which is 1.3.0.

**Comment by lwille** [comment]
Hi @martinschickbichlerspie, thanks for reporting! We're internally tracking this issue as INFRA-1556.

**Comment by lwille** [comment]
Sorry for the long wait, I've redeployed release 1.3.0. Can you please check that it's working for you?
