### ISSUE TITLE
how Input (object mail) is passed for mail-poll and delete

### ISSUE THREAD

**Issue by TEJAPS** [camunda-community-hub/camunda-platform-7-mail#36]

**Comment by TEJAPS** [comment]
Here I wanted to understand that as soon as any mail comes to my inbox,
how is it that: this workflow(https://github.com/camunda/camunda-bpm-mail/tree/master/examples/print-service) will get to know and execute.

Any help on this will be great

**Comment by saig0** [comment]
It is descripted here: 
* https://github.com/camunda/camunda-bpm-mail/tree/master/examples/print-service#using-the-mailnotificationservice
* https://github.com/camunda/camunda-bpm-mail#react-on-incoming-mails
