### ISSUE TITLE
how to integrate in existing docker distribution

### ISSUE THREAD

**Issue by dberardo-com** [camunda-community-hub/camunda-platform-7-mail#38]
Hello,

I have deployed camunda locally using this docker distribution: https://github.com/camunda/docker-camunda-bpm-platform/blob/next/README.md

I would expect the docker distribution to accept parameters to link an external SMTP server in order to send email to users, e.g. when they have to reset passwords or for any other sort of notification, but it seems to be missing here.

Apparently this is not an out-of-box functionality of the core camunda app, so i am trying to check for existing solution. Is this project one of those slutions?

And how do i integrate this bpm-mail extension in the docker distribution above? 

i am new to Camunda, thus i don't understand the difference between extension and plug in for the tool, but i am expecting to have to include a .war somewhere in a specific folder of the camunda core app. However, in the README of this project i cannot find any xml tag like `<plugin></plugin>` why?

**Comment by saig0** [comment]
Hi @dberardo-com,

good question. I don't know what is the recommended way to include the extension in the Docker distribution. 
You open an issue and ask the question in their repository :)

**Comment by dberardo-com** [comment]
thanks for the quick reply.

i could expand the existing docker image myself i think, but i would need to know more in general, how to add the email extension to camunda, since this is yet not 100% clear to me .

in this article i can read: https://camunda.com/blog/2016/06/camunda-bpm-mail/ that i have to "Add the extension as dependency to your POM:" 
which pom.xml is the documentation referring to? do i have to rebuild the whole camunda core app from scratch, or is the dependency loaded at runtime?

And should i first build the mail extension with maven and then add the "target" folder within the camunda core app before building that app again?

some more procedural (step by step) advise for non-java developers would be great.

thanks

**Comment by saig0** [comment]
You should ask about the recommended way in the Docker repo.

In general, you should copy/mount the available JAR in the `/lib` folder of the app server (i.e. tomcat). See here:
https://github.com/camunda-community-hub/camunda-bpm-mail#for-shared-process-engine

If the connectors plugin is configured then the mail connection should be available. Otherwise, you need to enable the connectors plugin first. See also:
https://github.com/camunda-community-hub/camunda-bpm-mail#how-to-use-it

Please let me know if and how it works. We can add the instructions to the README :rocket:

**Comment by dberardo-com** [comment]
thanks @saig0 i think it was all there in the Readme, but the camunda-specific glossary made that hard for me to find (no idea what is meant with "shared process engine") :D 

I will devote some time this week to this task and see if i am able to get somewhere. Will keep you posted

**Comment by celanthe** [comment]
Hi @dberardo-com! Thank you so much for opening this issue. If you're able to make note of any questions you have regarding glossary terms or any terminology used that you are finding challenging, it would be great if you would open a pull request to update the documentation with what you learn and solutions you've implemented as you dig into this task!
