### ISSUE TITLE
Error with "Maven install": Failed tests: PollMailConnectorTest.htmlMessage:169 expected:<"[html]"> but was:<"[<b>html</b>]">

### ISSUE THREAD

**Issue by superguddy** [camunda-community-hub/camunda-platform-7-mail#46]
The "Run as maven install" function returns an error when testing PollMailConnector:

Failed tests: 
PollMailConnectorTest.htmlMessage:169 expected:<"[html]"> but was:<"[<b>html</b>]">

Can someone help me correct the error?

**Comment by standev** [comment]
These are minor errors in tests, safe to ignore. You can either `mvn install -DskipTests` to ignore the tests, or fix the assertion in the test.

**Comment by jonathanlukas** [comment]
Hello @superguddy , could you please catch up with the `main` branch and try again. If the bug persists, feel free to open a new bug report.
