### ISSUE TITLE
Release 1.4.0

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-platform-7-mail#56]
Hi devrel team, 

could you please publish the version 1.4.0 of this extenion to maven central?

Thank you, Jonathan, Stephan and Ingo

**Comment by ingorichtsmeier** [comment]
After checking the output of the github action https://github.com/camunda-community-hub/camunda-platform-7-mail/runs/7875671760?check_suite_focus=true I could not find an upload to the nexus staging area.

Maybe the configuration of the github action didn't match the expected release settings?

**Comment by akeller** [comment]
@ingorichtsmeier sorry for not tagging you yesterday. Are you able to create a new release to see if this fixes the issue? This was successful with another project yesterday, so I'm hoping this will fix your issue as well 🤞

**Comment by ingorichtsmeier** [comment]
Hi @akeller, I will try it next week and keep you updated. 

Thank you for your investigation and clarification!

**Comment by ingorichtsmeier** [comment]
Hi @akeller,

I just tried to publish a new release 1.4.1, but unfortunately I could not find the upload to maven staging area in the output of the github actions.

I found the lines in this output:

``` 
2715: Deploy release to Camunda Repository using community-action-maven-release profile

3103: Deply release to Maven Central using profiles community-action-maven-release, oss-maven-central
```
But regarding to the details, both times the artifacts were uploaded to the camunda artifactory.

I will wait for [Jonathans pull request](https://github.com/camunda-community-hub/camunda-platform-7-mail/pull/57#issuecomment-1230359354) and try again afterwards.

**Comment by ingorichtsmeier** [comment]
After applying Jonathans pull request I get the same result: Uploading twice to camunda-artifactory, but not to nexus-staging.

We have to dig deeper...

**Comment by akeller** [comment]
Do the artifactId and the scm values need to be updated for the rename?

**Comment by ingorichtsmeier** [comment]
Hi @berndruecker and @jonathanlukas, the url for the distibution management was different to the one in the parent.

Now I found the upload to maven staging:
```
2022-09-05T13:51:47.6683089Z [INFO] Uploading to central: https://oss.sonatype.org//service/local/staging/deploy/maven2/org/camunda/bpm/extension/camunda-bpm-mail-extension-run/1.4.3/camunda-bpm-mail-extension-run-1.4.3.jar
2022-09-05T13:51:57.4657614Z [INFO] Uploaded to central: https://oss.sonatype.org//service/local/staging/deploy/maven2/org/camunda/bpm/extension/camunda-bpm-mail-extension-run/1.4.3/camunda-bpm-mail-extension-run-1.4.3.jar (653 kB at 67 kB/s)
```

Could you please press the button to release it? 

Thank you, Ingo

**Comment by berndruecker** [comment]
Released
