### ISSUE TITLE
Sending mails creates a new connection and they are never closed again

### ISSUE THREAD

**Issue by j-ulrich** [camunda-community-hub/camunda-platform-7-mail#93]
### Describe the bug

When using the `mail-send` connector, a new connection to the mail server is created and this connection is never closed.

We stumbled over this because a mail server started refusing mails with a messaging stating that there are too many open connections from the host running our Camunda instance.

### Steps to reproduce

1. Create a process with a task using the the `mail-send` connector.
2. Run the process multiple times.
3. Check the connections to the mail server (e.g. using `netstat`).

### Expected Behaviour

Either
1. The connector closes the connection after sending the mail.  
   or
2. There is only one connection to the mail server and this is reused.

The second option would be better in terms of performance but I don't know if there could be thread-safety problems when multiple (sub)processes are running in parallel.

For the first option, one could also think of making this configurable. Meaning: take an input like "keep-connection" and if it is set, the connection is not closed but instead, there is a method, for example on the `MailService`, which allows closing the current connection (transport). This would allow the process developer to have control about the lifetime of the connection.

### Library version

1.3.0

### Camunda version

7.17.0

### Camunda Distribution

Tomcat

**Comment by jonathanlukas** [comment]
Hello @j-ulrich , 

thank you for submitting feedback. 

I am currently working on a spring-boot-starter for this project that required some refinement of responsibilities of the components so I took the chance to have a look at connection management as well.

In #89 , your issues should be fixed as all connections (Store and Transport) are closed as soon as they are not needed anymore.

Currently, I am not planning to make this configurable as the number of concurrent connections should not be too high. If you have a different opinion and would like to see some kind of "connection pool", we can discuss this.

**Comment by j-ulrich** [comment]
That's fine for me! Thank you for the quick response!
